server:
  port: 8090
spring:
  application:
    name: my-workflow-app
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 10000
      fail-on-error: true
  cache:
    type: redis
    redis:
      time-to-live: 3600000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

camunda.bpm:
  deployment-resource-pattern:
    - classpath*:**/*.bpmn
  database:
    schema-update: true
  admin-user:
    id: admin
    password: "123456"
    first-name: Admin
    last-name: User
    email: admin@example.com
  generic-properties:
    enforce-history-time-to-live: false

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
momo:
  partnerCode: "MOMOBKUN20180529"
  accessKey: "klm05TvNBzhg7h7j"
  secretKey: "at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa"
  apiUrl: "https://test-payment.momo.vn/v2/gateway/api/create"
  redirectUrl: "http://localhost:4200/payment-success"
  ipnUrl: "https://pseudoemotional-unrequisitely-jeri.ngrok-free.dev/api/cart/momo-callback"
