
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/my-workflow-dev}
  datasource:
    url: ${DB_URL:jdbc:mysql://mysql-3046e449-tup20658-b458.d.aivencloud.com:20481/defaultdb?sslMode=REQUIRED}
    username: ${DB_USERNAME:avnadmin}
    password: ${DB_PASSWORD:AVNS_Kd7H_JPu_49mrZzF5Al}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

app:
  public-base-url: ${APP_PUBLIC_BASE_URL:http://localhost:8080}
  frontend-base-url: ${APP_FRONTEND_BASE_URL:http://localhost:4200}
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost}

keycloak:
  realm: ${KEYCLOAK_REALM:my-workflow-dev}

momo:
  redirectUrl: ${MOMO_REDIRECT_URL:http://localhost:4200/payment-success}
